gmp: Update to v6.3.0
AerynOS/recipes pull request #402
Opened 2024-10-05 15:09 UTC by Pheoxy

### Update GMP to v6.3.0

This pull request updates the GNU Multiple Precision Arithmetic Library (GMP) with the following enhancements:

#### Enhancements

1. **LTO (Link Time Optimization) Support**:
   - Added LTO support to improve the performance and optimization of the GMP library.

2. **Additional Make Checks**:
   - Included missing `make check` commands to ensure comprehensive testing during the build process.

2025-01-17 20:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/serpent-os/recipes?pullRequest=402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/serpent-os/recipes?pullRequest=402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/serpent-os/recipes?pullRequest=402) it.</sub>

2025-03-07 23:57 UTC, ReillyBrogan requested changes
Commits should be squashed, also we recently(ish) enabled LTO by default. That flag is no longer needed if you want it to continue using thin-lto. Alternately you can switch it to full LTO with `lto: full`

2025-03-08 05:27 UTC, Pheoxy commented
> Commits should be squashed, also we recently(ish) enabled LTO by default. That flag is no longer needed if you want it to continue using thin-lto. Alternately you can switch it to full LTO with `lto: full`

Thanks for the update. I deliberately kept the commits separate because I believe package version updates and other changes should remain distinct within the PR. Squashing them would mix these changes, making debugging more difficult later—even for a simple update like this.

Regarding the LTO flag, I appreciate the heads-up.

I don’t have the time to update this PR myself at the moment, but if someone else wants to take over, they’re welcome to.

2025-03-29 18:53 UTC, ReillyBrogan commented
Superceded by AerynOS/recipes#683 (I integrated all of your other changes into my version update).

2025-03-29 18:53 UTC, closed without merging